package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;

import java.util.Objects;

@Getter
@Setter
@ToString(exclude = "passwordHash")
@EqualsAndHashCode(exclude = {"login", "passwordHash"})
@Table("user")
public abstract class AbstractUser {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("login")
    private String login;

    @Column("password_hash")
    private String passwordHash;
}
