package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.Data;
import lombok.ToString;
import ua.maksym.hlushchenko.dao.db.sql.annotations.*;
import ua.maksym.hlushchenko.dao.entity.role.Admin;

import java.util.Objects;

@Data
@ToString(callSuper = true)
@Table("admin")
public class AdminImpl extends AbstractUserImpl implements Admin {

    @Id(value = "user_id", autoGenerated = false)
    private int id;

    @Override
    public Role getRole() {
        return Role.ADMIN;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if(!(o instanceof Admin)) return false;
        Admin admin = (Admin) o;
        return super.equals(o) &&
                getId() == admin.getId();
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getId());
    }
}
