package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;


@Getter
@Setter
@ToString(callSuper = true, exclude = "id")
@EqualsAndHashCode(callSuper = true)
@Table("admin")
public class Admin extends AbstractUser {
    @Id(value = "user_id", autoGenerated = false)
    private int id;

}
