package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.Table;

import java.util.Objects;

@Getter
@Setter
@ToString(callSuper = true, exclude = "id")
@EqualsAndHashCode(callSuper = true)
@Table("librarian")
public class Librarian extends AbstractUser {
    @Id(value = "id", autoGenerated = false)
    private int id;
}
