package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.*;
import ua.maksym.hlushchenko.dao.db.sql.annotations.*;
import ua.maksym.hlushchenko.dao.entity.role.Librarian;

import java.util.Objects;

@Data
@ToString(callSuper = true)
@Table("librarian")
public class LibrarianImpl extends AbstractUserImpl implements Librarian {

    @Id(value = "id", autoGenerated = false)
    private int id;

    @Override
    public Role getRole() {
        return Role.LIBRARIAN;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if(!(o instanceof Librarian)) return false;
        Librarian admin = (Librarian) o;
        return super.equals(o) &&
                getId() == admin.getId();
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getId());
    }
}
