package ua.maksym.hlushchenko.dao.entity.impl.role;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.Column;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.OneToMany;
import ua.maksym.hlushchenko.orm.annotations.Table;
import ua.maksym.hlushchenko.dao.entity.impl.Receipt;
import ua.maksym.hlushchenko.dao.entity.impl.Subscription;

import java.util.*;

@Getter
@Setter
@ToString(callSuper = true, exclude = {"id", "receipts", "subscriptions"})
@EqualsAndHashCode(callSuper = true)
@Table("reader")
public class Reader extends AbstractUser {
    @Id(value = "user_id", autoGenerated = false)
    private int id;

    @Column("blocked")
    private boolean blocked;

    @OneToMany(genericType = Receipt.class, mappedBy = "reader")
    private List<Receipt> receipts;

    @OneToMany(genericType = Subscription.class, mappedBy = "reader")
    private List<Subscription> subscriptions;
}
