package ua.maksym.hlushchenko.orm.entity.annotations;

import java.lang.annotation.*;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Id {
    String value();

    boolean autoGenerated();
}
