<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>${requestScope.book.title}</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>
                    Test
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Picture
            </td>
            <td>
                ${requestScope.book.description}
            </td>
        </tr>
        </tbody>
    </table>
</body>
</html>
