package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test7;

import ua.maksym.hlushchenko.orm.entity.annotations.Id;
import ua.maksym.hlushchenko.orm.entity.annotations.Table;

@Table("b")
public class B {
    @Id(value = "b_id", autoGenerated = false)
    private int bId;
}
