package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test8;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.entity.annotations.Id;
import ua.maksym.hlushchenko.orm.entity.annotations.Table;

@Getter
@Setter
@Table("b")
public class B extends A {
    @Id(value = "a_id", autoGenerated = false)
    private int aId;
}
