package ua.maksym.hlushchenko.dao.entity.role;

import lombok.*;
import ua.maksym.hlushchenko.orm.entity.annotations.Column;
import ua.maksym.hlushchenko.orm.entity.annotations.Id;
import ua.maksym.hlushchenko.orm.entity.annotations.Table;

@Getter
@Setter
@ToString(exclude = "passwordHash")
@EqualsAndHashCode(exclude = {"login", "passwordHash"})
@Table("user")
public abstract class AbstractUser {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("login")
    private String login;

    @Column("password_hash")
    private String passwordHash;
}
