package ua.maksym.hlushchenko.dao.entity;

import lombok.*;
import ua.maksym.hlushchenko.orm.entity.annotations.*;

import java.util.Objects;

@Getter
@Setter
@ToString
@Entity
@EqualsAndHashCode(exclude = {"name", "surname", "alias"})
@Table("author")
public class Author {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("name")
    private String name;

    @Column("surname")
    private String surname;

    @Column("alias")
    private String alias;

    @Override
    public boolean equals(Object entity) {
        if (this == entity) return true;
        if (!(entity instanceof Author)) return false;
        Author author = (Author) entity;
        return getId() == author.getId() &&
                Objects.equals(getName(), author.getName()) &&
                Objects.equals(getSurname(), author.getSurname()) &&
                Objects.equals(getAlias(), author.getAlias());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName(), getSurname(), getAlias());
    }
}
