package ua.maksym.hlushchenko.dao.entity;

import lombok.*;
import ua.maksym.hlushchenko.orm.entity.annotations.*;

import java.util.List;

@Getter
@Setter
@ToString(exclude = "books")
@EqualsAndHashCode(exclude = {"name", "books"})
@Entity
@Table("publisher")
public class Publisher {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("name")
    private String name;

    @OneToMany(genericType = Book.class,
            cascadeTypes = {CascadeType.SAVE, CascadeType.UPDATE},
            mappedBy = "publisher")
    private List<Book> books;
}
