package ua.maksym.hlushchenko.dao.entity;

import lombok.*;
import ua.maksym.hlushchenko.dao.entity.role.Reader;
import ua.maksym.hlushchenko.orm.entity.annotations.*;

import java.time.LocalDate;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = {"reader", "book", "takenDate", "broughtDate", "fine"})
@Entity
@Table("subscription")
public class Subscription {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @ManyToOne(cascadeTypes = {CascadeType.ALL})
    @JoinColumn("reader_id")
    private Reader reader;

    @ManyToOne(cascadeTypes = {CascadeType.ALL})
    @JoinColumn("book_id")
    private Book book;

    @Column("taken_date")
    private LocalDate takenDate;

    @Column("brought_date")
    private LocalDate broughtDate;

    @Column("fine")
    private double fine;
}
