package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test6;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.entity.annotations.Column;
import ua.maksym.hlushchenko.orm.entity.annotations.Id;
import ua.maksym.hlushchenko.orm.entity.annotations.Table;

@Getter
@Setter
@Table("a")
public class A {
    @Id(value = "a_id", autoGenerated = false)
    private int aId;

    @Column("a_column")
    private String aColumn;

    private double aFake;
}
