package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test4;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.entity.annotations.Column;
import ua.maksym.hlushchenko.orm.entity.annotations.Id;

@Getter
@Setter
public class A {
    @Id(value = "a_id", autoGenerated = false)
    private int aId;

    @Column("a_column")
    private String aColumn;

    private double aFake;
}
