package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test2;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.entity.annotations.*;

@Getter
@Setter
@Entity
@Table("a")
public class A {
    @Id(value = "a_id", autoGenerated = true)
    private int aId;

    @Column("a_column")
    private String aColumn;

    private double aFake;
}
