package ua.maksym.hlushchenko.orm.entity.entitiesForTest.test2;

import ua.maksym.hlushchenko.orm.entity.annotations.Column;
import ua.maksym.hlushchenko.orm.entity.annotations.Id;


public class B extends A {
    @Id(value = "b_id", autoGenerated = false)
    private int bId;

    @Column("b_column")
    private String bColumn;
}
