package ua.maksym.hlushchenko.dao.db.sql.entities.test2;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.annotations.Column;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.JoinColumn;
import ua.maksym.hlushchenko.orm.annotations.Table;

@Getter
@Setter
@Table("a")
public class A {
    @Id(value = "a_id", autoGenerated = false)
    private int aId;

    @Column("a_column")
    private String aColumn;

    @JoinColumn("a_join_column")
    private C aJoinColumn;

    private double aFake;
}
