package ua.maksym.hlushchenko.dao.db.sql.entities.test2;

import lombok.Getter;
import lombok.Setter;
import ua.maksym.hlushchenko.orm.annotations.Column;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.Table;

@Getter
@Setter
@Table("b")
public class C {
    @Id(value = "c_id", autoGenerated = false)
    private int cId;

    @Column("c_column")
    private String cColumn;

    private double cFake;
}
