package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;

import java.util.Objects;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = {"name", "surname", "alias"})
@Table("author_ua")
public class AuthorUa {
    @Id(value = "author_id", autoGenerated = false)
    private int id;

    @Column("name")
    private String name;

    @Column("surname")
    private String surname;

    @Column("alias")
    private String alias;
}
