package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.Data;
import ua.maksym.hlushchenko.dao.db.sql.annotations.*;
import ua.maksym.hlushchenko.dao.entity.Author;

import java.lang.annotation.Target;
import java.util.Objects;

@Data
@Table("author_ua")
public class AuthorUaImpl implements Author {

    @Id(value = "author_id", autoGenerated = false)
    private int id;

    @Column("name")
    private String name;

    @Column("surname")
    private String surname;

    @Column("alias")
    private String alias;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Author)) return false;
        Author author = (Author) o;
        return getId() == author.getId() &&
                Objects.equals(getName(), author.getName()) &&
                Objects.equals(getSurname(), author.getSurname()) &&
                Objects.equals(getAlias(), author.getAlias());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName(), getSurname(), getAlias());
    }
}
