package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = {"name", "surname", "alias"})
@Table("author")
public class Author {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("name")
    private String name;

    @Column("surname")
    private String surname;

    @Column("alias")
    private String alias;
}
