package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.Data;
import ua.maksym.hlushchenko.dao.db.sql.annotations.*;
import ua.maksym.hlushchenko.dao.entity.*;

import java.time.LocalDate;
import java.util.*;

@Data
@Table("book")
public class BookImpl implements Book {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("title")
    private String title;

    @ManyToOne(relatedEntity = AuthorImpl.class)
    @JoinColumn(value = "author_id")
    private Author author;

    @ManyToOne(relatedEntity = PublisherImpl.class)
    @JoinColumn(value = "publisher_id")
    private Publisher publisher;

    @Column("publication_date")
    private LocalDate date;

    @Column("description")
    private String description;

    @Column("cover_path")
    private String coverPath;

    @ManyToMany(relatedEntity = GenreImpl.class,
            joinTable = @JoinTable(name = "book_has_genre",
                    joinColumn = "book_id",
                    inverseColumn = "genre_id"))
    private List<Genre> genres;

    @ManyToMany(relatedEntity = ReceiptImpl.class, mappedBy = "books")
    private List<Receipt> receipts;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Book)) return false;
        Book book = (Book) o;

        return getId() == book.getId() &&
                getAuthor().equals(book.getAuthor()) &&
                getPublisher().equals(book.getPublisher()) &&
                getDate().equals(book.getDate()) &&
                getTitle().equals(book.getTitle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getTitle(), getAuthor(), getPublisher(), getDate());
    }
}
