package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;

import java.time.LocalDate;
import java.util.*;

@Getter
@Setter
@ToString(exclude = {"genres", "receipts"})
@EqualsAndHashCode(exclude = {"title", "author", "publisher",
        "date", "description", "coverPath", "genres", "receipts"})
@Table("book")
public class Book {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("title")
    private String title;

    @ManyToOne
    @JoinColumn("author_id")
    private Author author;

    @ManyToOne
    @JoinColumn("publisher_id")
    private Publisher publisher;

    @Column("publication_date")
    private LocalDate date;

    @Column("description")
    private String description;

    @Column("cover_path")
    private String coverPath;

    @ManyToMany(genericType = Genre.class)
    @JoinTable(name = "book_has_genre",
            joinColumn = "book_id",
            inverseColumn = "genre_id")
    private List<Genre> genres;

    @ManyToMany(genericType = Receipt.class, mappedBy = "books")
    private List<Receipt> receipts;
}
