package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.Data;
import ua.maksym.hlushchenko.dao.db.sql.annotations.*;
import ua.maksym.hlushchenko.dao.entity.Book;
import ua.maksym.hlushchenko.dao.entity.Genre;

import java.util.List;
import java.util.Objects;

@Data
@Table("genre")
public class GenreImpl implements Genre {
    @Id(value = "id", autoGenerated = false)
    private int id;

    @Column("name")
    private String name;

    @ManyToMany(mappedBy = "genres", relatedEntity = BookImpl.class)
    private List<Book> books;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ua.maksym.hlushchenko.dao.entity.Genre)) return false;
        ua.maksym.hlushchenko.dao.entity.Genre genre = (ua.maksym.hlushchenko.dao.entity.Genre) o;
        return getId() == genre.getId() &&
                Objects.equals(getName(), genre.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName());
    }
}
