package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.*;

import java.util.List;

@Getter
@Setter
@ToString(exclude = "books")
@EqualsAndHashCode(exclude = {"name", "books"})
@Table("genre")
public class Genre {
    @Id(value = "id", autoGenerated = false)
    private int id;

    @Column("name")
    private String name;

    @ManyToMany(genericType = Book.class, mappedBy = "genres")
    private List<Book> books;
}
