package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.Column;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.Table;

import java.util.Objects;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = "name")
@Table("genre_ua")
public class GenreUa {
    @Id(value = "genre_id", autoGenerated = false)
    private int id;

    @Column("name")
    private String name;
}
