package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.orm.annotations.Id;
import ua.maksym.hlushchenko.orm.annotations.Column;
import ua.maksym.hlushchenko.orm.annotations.Table;

import java.util.Objects;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = "name")
@Table("publisher")
public class Publisher {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("name")
    private String name;
}
