package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.Data;
import ua.maksym.hlushchenko.dao.db.sql.annotations.Id;
import ua.maksym.hlushchenko.dao.db.sql.annotations.Column;
import ua.maksym.hlushchenko.dao.db.sql.annotations.Table;
import ua.maksym.hlushchenko.dao.entity.Publisher;

import java.util.Objects;

@Data
@Table("publisher")
public class PublisherImpl implements Publisher {

    @Id(value = "id", autoGenerated = true)
    private int id;

    @Column("name")
    private String name;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Publisher)) return false;
        Publisher publisher = (Publisher) o;
        return Objects.equals(getId(), publisher.getId()) &&
                Objects.equals(getName(), publisher.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName());
    }
}
