package ua.maksym.hlushchenko.dao.entity.impl;

import lombok.*;
import ua.maksym.hlushchenko.dao.entity.impl.role.Reader;
import ua.maksym.hlushchenko.orm.annotations.*;

import java.time.LocalDate;

@Getter
@Setter
@ToString
@EqualsAndHashCode(exclude = {"reader", "book", "takenDate", "broughtDate", "fine"})
@Table("subscription")
public class Subscription {
    @Id(value = "id", autoGenerated = true)
    private int id;

    @ManyToOne
    @JoinColumn("reader_id")
    private Reader reader;

    @OneToOne
    @JoinColumn("book_id")
    private Book book;

    @Column("taken_date")
    private LocalDate takenDate;

    @Column("brought_date")
    private LocalDate broughtDate;

    @Column("fine")
    private double fine;
}
